// Lightweight keyword detection for the Bid Opportunities feed — no AI call,
// just substring matching so this is instant and free to run on every page load.

// South Florida municipalities (Miami-Dade, Broward, Palm Beach). Longest
// names first so "North Miami Beach" matches before the shorter "Miami"
// would incorrectly match inside it.
const MUNICIPALITIES = [
  "Unincorporated Miami-Dade",
  "Miami-Dade County",
  "North Miami Beach",
  "Lauderdale-by-the-Sea",
  "West Palm Beach",
  "Palm Beach Gardens",
  "Palm Beach Shores",
  "Royal Palm Beach",
  "North Palm Beach",
  "South Palm Beach",
  "Village of Golf",
  "Boynton Beach",
  "Jupiter Inlet Colony",
  "Lake Clarke Shores",
  "Lake Worth Beach",
  "Hallandale Beach",
  "Pompano Beach",
  "Deerfield Beach",
  "Highland Beach",
  "Delray Beach",
  "Boca Raton",
  "Fort Lauderdale",
  "Coral Springs",
  "Coconut Creek",
  "Cooper City",
  "Dania Beach",
  "Davie",
  "Hillsboro Beach",
  "Hollywood",
  "Lauderdale Lakes",
  "Lauderhill",
  "Lighthouse Point",
  "Margate",
  "Miramar",
  "North Lauderdale",
  "Oakland Park",
  "Parkland",
  "Pembroke Park",
  "Pembroke Pines",
  "Plantation",
  "Southwest Ranches",
  "Sunrise",
  "Tamarac",
  "Weston",
  "West Park",
  "Wilton Manors",
  "Atlantis",
  "Belle Glade",
  "Briny Breezes",
  "Cloud Lake",
  "Glen Ridge",
  "Greenacres",
  "Gulf Stream",
  "Haverhill",
  "Hypoluxo",
  "Juno Beach",
  "Jupiter",
  "Lake Park",
  "Lantana",
  "Loxahatchee Groves",
  "Manalapan",
  "Mangonia Park",
  "Ocean Ridge",
  "Pahokee",
  "Palm Beach",
  "Riviera Beach",
  "South Bay",
  "Tequesta",
  "Wellington",
  "Westlake",
  "Miami Beach",
  "Coral Gables",
  "Hialeah Gardens",
  "Hialeah",
  "Miami Springs",
  "North Miami",
  "Opa-locka",
  "South Miami",
  "Homestead",
  "Miami Shores",
  "Bal Harbour",
  "Bay Harbor Island",
  "Surfside",
  "West Miami",
  "Florida City",
  "Biscayne Park",
  "El Portal",
  "Golden Beach",
  "Pinecrest",
  "Indian Creek",
  "Medley",
  "North Bay Village",
  "Key Biscayne",
  "Sweetwater",
  "Virginia Gardens",
  "Aventura",
  "Islandia",
  "Sunny Isles Beach",
  "Miami Lakes",
  "Palmetto Bay",
  "Miami Gardens",
  "Doral",
  "Cutler Bay",
  "Miami",
];

const TRADES: { label: string; keywords: string[] }[] = [
  { label: "Plumbing", keywords: ["plumbing", "plumber"] },
  { label: "Roofing", keywords: ["roofing", "roof replacement", "re-roof"] },
  { label: "Electrical", keywords: ["electrical", "electrician"] },
  { label: "HVAC", keywords: ["hvac", "air conditioning", "mechanical"] },
  { label: "Paving/Asphalt", keywords: ["paving", "asphalt", "resurfacing", "road resurfacing"] },
  { label: "Concrete", keywords: ["concrete", "sidewalk"] },
  { label: "Landscaping", keywords: ["landscap", "irrigation"] },
  { label: "Painting", keywords: ["painting"] },
  { label: "Flooring", keywords: ["flooring"] },
  { label: "Drywall", keywords: ["drywall"] },
  { label: "Masonry", keywords: ["masonry"] },
  { label: "Fencing", keywords: ["fencing", "fence"] },
  { label: "Water/Sewer", keywords: ["water main", "sewer", "utilities"] },
  { label: "Fire Protection", keywords: ["fire protection", "sprinkler"] },
  { label: "Demolition", keywords: ["demolition", "demo of"] },
  { label: "Sitework", keywords: ["sitework", "excavation", "grading"] },
  { label: "General Contracting", keywords: ["general contract", "renovation", "construction of"] },
];

export function detectMunicipality(text: string): string | null {
  const lower = text.toLowerCase();
  for (const name of MUNICIPALITIES) {
    if (lower.includes(name.toLowerCase())) return name;
  }
  return null;
}

export function detectTrade(text: string): string | null {
  const lower = text.toLowerCase();
  for (const trade of TRADES) {
    if (trade.keywords.some((kw) => lower.includes(kw))) return trade.label;
  }
  return null;
}
