-- AlterEnum
ALTER TYPE "BidSource" ADD VALUE 'HIALEAH_GARDENS';
ALTER TYPE "BidSource" ADD VALUE 'DORAL';
ALTER TYPE "BidSource" ADD VALUE 'MIAMI_SPRINGS';
ALTER TYPE "BidSource" ADD VALUE 'MIAMI_SHORES';
