-- AlterEnum
ALTER TYPE "BidSource" ADD VALUE 'MIAMI';
ALTER TYPE "BidSource" ADD VALUE 'MIAMI_BEACH';
ALTER TYPE "BidSource" ADD VALUE 'NORTH_MIAMI';
ALTER TYPE "BidSource" ADD VALUE 'BAY_HARBOR_ISLANDS';
ALTER TYPE "BidSource" ADD VALUE 'OPA_LOCKA';
ALTER TYPE "BidSource" ADD VALUE 'FLORIDA_CITY';
ALTER TYPE "BidSource" ADD VALUE 'SURFSIDE';
ALTER TYPE "BidSource" ADD VALUE 'CUTLER_BAY';
